kind: SwitchConfig
hooks:
  - name: demo-hook
    type: Executable
    path: /Users/<your-user>/go/src/github.com/danielfoehrkn/kubeconfig-switch/resources/config/hook-with-args/demo-executable.sh
    arguments:
      - "--name bernd"
    execution:
      interval: 10m