kind: SwitchConfig
version: v1alpha1
kubeconfigStores:
- kind: filesystem
  paths:
  - ~/.kube/my-kubeconfig-files
  required: null
  config: null
- kind: vault
  paths:
  - landscapes
  config:
    vaultAPIAddress: http://127.0.0.1:8200
