# config that specifies search locations in both vault and filesystem
kind: SwitchConfig
# default vault API Address - can be overridden by flag or environment variable (see docs)
vaultAPIAddress: "http://127.0.0.1:8200"
kubeconfigPaths:
  #  possible to specify only one specific file on the filesystem
  - path: "~/.kube/config"
    store: filesystem
  - path: "~/.kube/my-other-kubeconfigs/"
    store: filesystem
  - path: "landscapes"
    store: vault